	package com.simple.cms.model;
	
	
	/**
	* Article generated by hbm2java
	*/
	public class Article  implements java.io.Serializable {
	
	
	  private Integer articleId;
	  private User user;
	  private int number;
	  private String name;
	  private String description;
	  private String picture;
	
	 public Article() {
	 }
	
		
	 public Article(User user, int number) {
	     this.user = user;
	     this.number = number;
	 }
	 public Article(User user, int number, String name, String description, String picture) {
	    this.user = user;
	    this.number = number;
	    this.name = name;
	    this.description = description;
	    this.picture = picture;
	 }
	
	 public Integer getArticleId() {
	     return this.articleId;
	 }
	 
	 public void setArticleId(Integer articleId) {
	     this.articleId = articleId;
	 }
	 public User getUser() {
	     return this.user;
	 }
	 
	 public void setUser(User user) {
	     this.user = user;
	 }
	 public int getNumber() {
	     return this.number;
	 }
	 
	 public void setNumber(int number) {
	     this.number = number;
	 }
	 public String getName() {
	     return this.name;
	 }
	 
	 public void setName(String name) {
	     this.name = name;
	 }
	 public String getDescription() {
	     return this.description;
	 }
	 
	 public void setDescription(String description) {
	     this.description = description;
	 }
	 public String getPicture() {
	     return this.picture;
	 }
	 
	 public void setPicture(String picture) {
	     this.picture = picture;
	 }
	
	 @Override
		public String toString() {
			return "Article [ number=" + number
					+ ", name=" + name + ", description=" + description+ "]";
		}
	
	}
	
	
